/**
用户表
 */
DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user`(
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  uname varchar(32) NOT NULL COMMENT '账号',
  password VARCHAR(512) NOT NULL COMMENT '密码',
  name VARCHAR(225) DEFAULT NULL COMMENT '名称',
  type INT(2) DEFAULT NULL COMMENT '类型',
  sex INT(2) DEFAULT NULL COMMENT '性别',
  age INT(4) DEFAULT NULL COMMENT '年龄',
  tel VARCHAR(32) DEFAULT NULL COMMENT '电话',
  adress VARCHAR(225) DEFAULT NULL COMMENT '地址',
  PRIMARY KEY (id),
  UNIQUE KEY idx_uname (uname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
